### ISSUE TITLE
Hostile mobs don't spawn with servercore installed

### ISSUE THREAD

**Issue by PolyframeX** [Wesley1808/ServerCore#103]
**Describe the bug**
When playing with servercore installed, all hostile mobs stop spawning.

**Reproduce**
1) Install servercore

**Expected behavior**
Hostile mobs should spawn

**Versions** -Latest is not a version!
ServerCore: 1.5.1 forge
Minecraft: 1.20.1

**Mod incompatibilities**
There are no other mods installed.

**Comment by Wesley1808** [comment]
Can you provide your config.yml / log file? I know of a bug with faulty configurations (errors would be logged) that could potentially cause this.

**Comment by PolyframeX** [comment]
This is my log here (changed to .txt for github) [config.txt](https://github.com/Wesley1808/ServerCore/files/15494153/config.txt)

**Comment by Wesley1808** [comment]
There are a lot of modded mob categories in there that the mod would be unable to recognize if you are running with no other mods installed. Try removing these.

```yml
    - category: 'GLARES'
      mobcap: 15
      spawn-interval: 1

    - category: 'RASCALS'
      mobcap: 1
      spawn-interval: 1

    - category: 'WILDERWILDFIREFLIES'
      mobcap: 56
      spawn-interval: 1

    - category: 'WILDERWILDJELLYFISH'
      mobcap: 30
      spawn-interval: 1

    - category: 'WILDERWILDCRAB'
      mobcap: 25
      spawn-interval: 1

    - category: 'WILDERWILDTUMBLEWEED'
      mobcap: 10
      spawn-interval: 1

    - category: 'ha_fish'
      mobcap: 5
      spawn-interval: 1

    - category: 'ha_fish_underground'
      mobcap: 5
      spawn-interval: 1

    - category: 'ha_squid'
      mobcap: 5
      spawn-interval: 1

    - category: 'ha_squid_underground'
      mobcap: 5
      spawn-interval: 1

    - category: 'ha_jelly'
      mobcap: 5
      spawn-interval: 1

    - category: 'ha_jelly_underground'
      mobcap: 3
      spawn-interval: 1

    - category: 'ha_shark'
      mobcap: 5
      spawn-interval: 400

    - category: 'crustacean'
      mobcap: 5
      spawn-interval: 1

    - category: 'crustacean_underground'
      mobcap: 3
      spawn-interval: 1

    - category: 'ha_critter'
      mobcap: 5
      spawn-interval: 1
 ```
