### ISSUE TITLE
Server crashes on load

### ISSUE THREAD

**Issue by miclol** [Wesley1808/ServerCore#72]
**Describe the bug**
Loading the server on an itzg-docker Minecraft server with several other performance-enhancing mods crashes the server on load.

**Reproduce**
Steps to reproduce the behaviour:
1. Create a docker Minecraft server with a docker compose of the following:
```
version: "3.8"

services:
  minecraft:
    container_name: mc-1.20-paper-survival
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
      - 19132:19132/udp
    volumes:
      - "./1.20 Survival:/data"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: FABRIC
      MEMORY: 6G
      EXEC_DIRECTLY: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
```
2. Load server with these mods: C2ME, Carpet, Carpet Extra, Fabric API, Fabric Kotlin, Ferrite Core, Geyser, Floodgate, Krypton, Ledger, Lithium, Modernfix, Starlight, ViewDistanceFix, VMP
3. Crash.

**Expected behaviour**
For it to not crash.

**Versions**
ServerCore: 1.3.7
Minecraft: 1.20.1

**Crash Report**
[crash-2023-08-25_11.15.37-server.txt](https://github.com/Wesley1808/ServerCore/files/12439000/crash-2023-08-25_11.15.37-server.txt)
